const drafts=new Map();
let reportBusy=false;
function reportKey(){return `${selected}:${template}`;}
function enhanceReports(){
 if(page!=='학습보고서')return;
 const controls=document.querySelector('.controls'),report=document.querySelector('.report');
 controls.insertAdjacentHTML('beforeend','<div class="toolbar"><button id="ai-report" class="primary">AI 보고서 생성</button><button id="ai-notice">AI 안내문 생성</button></div><div class="toolbar"><button id="save-image">이미지 저장</button><button id="save-pdf">PDF 저장</button><button id="share-report">휴대폰 공유</button></div><p class="muted">AI 초안은 선생님이 내용을 확인한 뒤 공유해주세요. 휴대폰 공유창에서 카카오톡을 선택할 수 있습니다.</p><p id="ai-status" role="status"></p>');
 const notice=controls.querySelector('.notice');notice.textContent='학습정보로 만든 미리보기입니다. AI 생성 시 학년·과목·점수·학습 내용을 OpenAI로 전달하며, 학생 이름은 제외합니다.';
 const existing=drafts.get(reportKey());if(existing)showDraft(existing);
 document.getElementById('ai-report').onclick=()=>generateReport(template);
 document.getElementById('ai-notice').onclick=()=>generateReport('안내문');
 document.getElementById('save-image').onclick=async()=>{try{download(await reportImage(),`멘사-학습보고서-${today()}.png`)}catch{notify('이미지 저장에 실패했습니다. 다시 시도해주세요.')}};
 document.getElementById('save-pdf').onclick=()=>{notify('인쇄 창에서 PDF로 저장을 선택하세요.');window.print()};
 document.getElementById('share-report').onclick=shareReport;
}
function showDraft(d){const report=document.querySelector('.report');report.innerHTML=`<span class="tag">${esc(d.kind)} · AI 초안</span><h2>멘사창의영재센터 ${d.kind==='안내문'?'학부모 안내문':'학습보고서'}</h2><p>${esc(student().name)} · ${esc(student().grade)} · ${today()}</p><div id="draft-text" contenteditable="true" role="textbox" aria-label="AI 초안 수정" aria-multiline="true" style="white-space:pre-wrap;outline-offset:5px">${esc(d.text)}</div>`;document.getElementById('draft-text').oninput=e=>{d.text=e.target.innerText};}
async function generateReport(kind){if(reportBusy)return;reportBusy=true;const key=reportKey();const s={...student()};const status=document.getElementById('ai-status');status.textContent='AI 초안을 만들고 있습니다…';document.getElementById('ai-report').disabled=true;document.getElementById('ai-notice').disabled=true;
try{const response=await fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({template:kind,student:{grade:s.grade,subject:s.subject,before:s.before,score:s.score,topic:s.topic,last:s.last,comment:s.comment,goal:s.goal}}),signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok)throw Error(result.error||'생성에 실패했습니다.');const draft={kind,text:result.text};drafts.set(key,draft);if(page==='학습보고서'&&reportKey()===key){showDraft(draft);status.textContent='초안을 만들었습니다. 보고서 본문을 눌러 수정할 수 있습니다.';}}catch(e){if(status.isConnected)status.textContent=e.name==='TimeoutError'?'생성 시간이 길어졌습니다. 다시 시도해주세요.':e.message;}finally{reportBusy=false;document.getElementById('ai-report')?.removeAttribute('disabled');document.getElementById('ai-notice')?.removeAttribute('disabled');}}
function reportLines(){const report=document.querySelector('.report');return Array.from(report.children).flatMap(el=>{if(el.tagName==='LABEL')return[(el.querySelector('input')?.checked?'[완료] ':'[ ] ')+el.textContent.trim()];return el.innerText.split('\n')}).filter(Boolean);}
async function reportImage(){await document.fonts.ready;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1200;ctx.font='28px system-ui, sans-serif';const lines=[];for(const paragraph of reportLines()){let line='';for(const ch of paragraph){if(ctx.measureText(line+ch).width>1040){lines.push(line);line=ch}else line+=ch}lines.push(line,'');}canvas.height=Math.max(800,180+lines.length*44);ctx.fillStyle='#fff';ctx.fillRect(0,0,1200,canvas.height);ctx.fillStyle='#214ed6';ctx.fillRect(0,0,1200,16);ctx.font='28px system-ui, sans-serif';ctx.fillStyle='#18253c';lines.forEach((line,i)=>ctx.fillText(line,80,100+i*44));return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('이미지 생성 실패')),'image/png'));}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function shareReport(){try{const blob=await reportImage();const file=new File([blob],`멘사-학습보고서-${today()}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'멘사창의영재센터 학습보고서'});}else{download(blob,file.name);notify('이미지를 저장했습니다. 카카오톡에서 사진으로 첨부해주세요.');}}catch(e){if(e.name!=='AbortError')notify('공유창을 열 수 없습니다. 이미지 저장 후 카카오톡에 첨부해주세요.');}}
